CREATE TABLE IF NOT EXISTS ascendany.students (
    student_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    canonical_key TEXT NOT NULL UNIQUE,
    canonical_name TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS students_canonical_name_idx
    ON ascendany.students (canonical_name);

