CREATE TABLE IF NOT EXISTS ascendany.student_identities (
    identity_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES ascendany.students(student_id) ON DELETE RESTRICT,
    source TEXT NOT NULL,
    external_id TEXT NOT NULL,
    external_name TEXT,
    meta JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS student_identities_source_external_id_uniq
    ON ascendany.student_identities (source, external_id);

CREATE INDEX IF NOT EXISTS student_identities_student_id_idx
    ON ascendany.student_identities (student_id);

