CREATE TABLE IF NOT EXISTS ascendany.exams (
    exam_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_type TEXT NOT NULL,
    source_path TEXT NOT NULL,
    title TEXT,
    starts_at TIMESTAMPTZ,
    ends_at TIMESTAMPTZ,
    duration_seconds INTEGER,
    total_points NUMERIC,
    meta JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (exam_type, source_path)
);

CREATE INDEX IF NOT EXISTS exams_starts_at_idx
    ON ascendany.exams (starts_at);

