CREATE TABLE IF NOT EXISTS ascendany.exam_files (
    exam_file_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id BIGINT NOT NULL REFERENCES ascendany.exams(exam_id) ON DELETE CASCADE,
    file_role TEXT NOT NULL,
    relative_path TEXT NOT NULL,
    sha256 TEXT NOT NULL,
    size_bytes BIGINT,
    mtime TIMESTAMPTZ,
    imported_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS exam_files_exam_id_relative_path_sha256_uniq
    ON ascendany.exam_files (exam_id, relative_path, sha256);

CREATE INDEX IF NOT EXISTS exam_files_exam_id_idx
    ON ascendany.exam_files (exam_id);

