CREATE TABLE IF NOT EXISTS ascendany.exam_problems (
    exam_problem_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id BIGINT NOT NULL REFERENCES ascendany.exams(exam_id) ON DELETE CASCADE,
    problem_code TEXT NOT NULL,
    problem_title TEXT,
    problem_kind TEXT,
    group_code TEXT,
    group_name TEXT,
    points NUMERIC,
    order_idx INTEGER,
    meta JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (exam_id, problem_code)
);

CREATE INDEX IF NOT EXISTS exam_problems_exam_id_idx
    ON ascendany.exam_problems (exam_id);

