CREATE TABLE IF NOT EXISTS ascendany.submissions (
    submission_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id BIGINT NOT NULL REFERENCES ascendany.exams(exam_id) ON DELETE CASCADE,
    student_id BIGINT REFERENCES ascendany.students(student_id) ON DELETE RESTRICT,
    actor_source TEXT NOT NULL,
    actor_external_id TEXT NOT NULL,
    actor_name TEXT,
    submitted_at TIMESTAMPTZ,
    problem_code TEXT,
    verdict TEXT,
    score NUMERIC,
    language TEXT,
    time_ms INTEGER,
    memory_kb INTEGER,
    row_hash TEXT NOT NULL,
    raw JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE IF EXISTS ascendany.submissions
    ALTER COLUMN student_id DROP NOT NULL;

ALTER TABLE IF EXISTS ascendany.submissions
    ADD COLUMN IF NOT EXISTS actor_source TEXT,
    ADD COLUMN IF NOT EXISTS actor_external_id TEXT,
    ADD COLUMN IF NOT EXISTS actor_name TEXT;

UPDATE ascendany.submissions
SET actor_source = COALESCE(actor_source, 'legacy_student_id'),
    actor_external_id = COALESCE(actor_external_id, COALESCE(student_id::text, 'unknown')),
    actor_name = COALESCE(actor_name, NULL)
WHERE actor_source IS NULL
   OR actor_external_id IS NULL;

ALTER TABLE IF EXISTS ascendany.submissions
    ALTER COLUMN actor_source SET NOT NULL,
    ALTER COLUMN actor_external_id SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS submissions_exam_id_row_hash_uniq
    ON ascendany.submissions (exam_id, row_hash);

CREATE INDEX IF NOT EXISTS submissions_exam_id_student_id_idx
    ON ascendany.submissions (exam_id, student_id);

CREATE INDEX IF NOT EXISTS submissions_student_id_submitted_at_idx
    ON ascendany.submissions (student_id, submitted_at);

CREATE INDEX IF NOT EXISTS submissions_exam_actor_idx
    ON ascendany.submissions (exam_id, actor_source, actor_external_id);
