CREATE TABLE IF NOT EXISTS ascendany.submissions (
    submission_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id BIGINT NOT NULL REFERENCES ascendany.exams(exam_id) ON DELETE CASCADE,
    student_id BIGINT NOT NULL REFERENCES ascendany.students(student_id) ON DELETE RESTRICT,
    submitted_at TIMESTAMPTZ,
    problem_code TEXT,
    verdict TEXT,
    score NUMERIC,
    language TEXT,
    time_ms INTEGER,
    memory_kb INTEGER,
    row_hash TEXT NOT NULL,
    raw JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS submissions_exam_id_row_hash_uniq
    ON ascendany.submissions (exam_id, row_hash);

CREATE INDEX IF NOT EXISTS submissions_exam_id_student_id_idx
    ON ascendany.submissions (exam_id, student_id);

CREATE INDEX IF NOT EXISTS submissions_student_id_submitted_at_idx
    ON ascendany.submissions (student_id, submitted_at);

