CREATE TABLE IF NOT EXISTS ascendany.ingest_runs (
    ingest_run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status TEXT NOT NULL,
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at TIMESTAMPTZ,
    meta JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS ingest_runs_started_at_idx
    ON ascendany.ingest_runs (started_at);

