CREATE TABLE IF NOT EXISTS ascendany.user_accounts (
    account_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL,
    username_normalized TEXT GENERATED ALWAYS AS (lower(BTRIM(username))) STORED,
    password_hash TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_login_at TIMESTAMPTZ
);

ALTER TABLE ascendany.user_accounts
    DROP CONSTRAINT IF EXISTS user_accounts_username_not_blank;
ALTER TABLE ascendany.user_accounts
    ADD CONSTRAINT user_accounts_username_not_blank
    CHECK (BTRIM(username) <> '');

CREATE UNIQUE INDEX IF NOT EXISTS user_accounts_username_normalized_uniq
    ON ascendany.user_accounts (username_normalized);
