CREATE TABLE IF NOT EXISTS ascendany.user_contacts (
    contact_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL REFERENCES ascendany.user_accounts(account_id) ON DELETE CASCADE,
    type TEXT NOT NULL,
    value TEXT NOT NULL,
    value_normalized TEXT GENERATED ALWAYS AS (lower(BTRIM(value))) STORED,
    is_verified BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE ascendany.user_contacts
    DROP CONSTRAINT IF EXISTS user_contacts_type_check;
ALTER TABLE ascendany.user_contacts
    ADD CONSTRAINT user_contacts_type_check
    CHECK (type IN ('phone', 'email'));

ALTER TABLE ascendany.user_contacts
    DROP CONSTRAINT IF EXISTS user_contacts_value_not_blank;
ALTER TABLE ascendany.user_contacts
    ADD CONSTRAINT user_contacts_value_not_blank
    CHECK (BTRIM(value) <> '');

CREATE UNIQUE INDEX IF NOT EXISTS user_contacts_type_value_normalized_uniq
    ON ascendany.user_contacts (type, value_normalized);

CREATE INDEX IF NOT EXISTS user_contacts_account_id_idx
    ON ascendany.user_contacts (account_id);
