CREATE TABLE IF NOT EXISTS ascendany.user_refresh_tokens (
    token_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL REFERENCES ascendany.user_accounts(account_id) ON DELETE CASCADE,
    token_hash TEXT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    device_id TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS user_refresh_tokens_token_hash_uniq
    ON ascendany.user_refresh_tokens (token_hash);

CREATE INDEX IF NOT EXISTS user_refresh_tokens_account_id_idx
    ON ascendany.user_refresh_tokens (account_id);
