CREATE TABLE IF NOT EXISTS ascendany.user_auto_analysis_cache (
    cache_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL REFERENCES ascendany.user_accounts(account_id) ON DELETE CASCADE,
    exam_id BIGINT NOT NULL REFERENCES ascendany.exams(exam_id) ON DELETE CASCADE,
    role_id TEXT NOT NULL DEFAULT 'xiaoD',
    provider_type TEXT,
    reply TEXT NOT NULL,
    source TEXT NOT NULL DEFAULT 'online',
    generated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    delivered_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (account_id, exam_id, role_id)
);

CREATE INDEX IF NOT EXISTS user_auto_analysis_cache_account_idx
    ON ascendany.user_auto_analysis_cache (account_id, exam_id DESC);

CREATE INDEX IF NOT EXISTS user_auto_analysis_cache_exam_idx
    ON ascendany.user_auto_analysis_cache (exam_id, role_id);
