CREATE TABLE IF NOT EXISTS ascendany.student_nickname_claims (
    claim_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES ascendany.students(student_id) ON DELETE RESTRICT,
    nickname TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    claimed_from TIMESTAMPTZ NOT NULL DEFAULT now(),
    claimed_to TIMESTAMPTZ,
    claimed_by_account_id BIGINT REFERENCES ascendany.user_accounts(account_id) ON DELETE SET NULL,
    meta JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE UNIQUE INDEX IF NOT EXISTS student_nickname_claims_active_nickname_uniq
    ON ascendany.student_nickname_claims (nickname)
    WHERE is_active = TRUE;

CREATE INDEX IF NOT EXISTS student_nickname_claims_student_id_idx
    ON ascendany.student_nickname_claims (student_id);

CREATE INDEX IF NOT EXISTS student_nickname_claims_nickname_idx
    ON ascendany.student_nickname_claims (nickname);

-- Migration helper (idempotent):
-- Seed active nickname claims from existing user profiles when student_no can be resolved.
INSERT INTO ascendany.student_nickname_claims (
    student_id,
    nickname,
    is_active,
    claimed_by_account_id,
    meta
)
SELECT
    si.student_id,
    BTRIM(up.pta_nickname) AS nickname,
    TRUE,
    up.account_id,
    jsonb_build_object('migrated_from', 'user_profiles')
FROM ascendany.user_profiles AS up
JOIN ascendany.student_identities AS si
  ON si.external_id = BTRIM(up.student_id)
 AND si.source LIKE '%student_no'
WHERE NULLIF(BTRIM(up.student_id), '') IS NOT NULL
  AND NULLIF(BTRIM(up.pta_nickname), '') IS NOT NULL
ON CONFLICT (nickname) WHERE (is_active = TRUE) DO NOTHING;

-- Migration helper (idempotent):
-- Persist nickname identity for active claims, so nickname lookup is explicit.
INSERT INTO ascendany.student_identities (
    student_id,
    source,
    external_id,
    external_name
)
SELECT
    snc.student_id,
    'pta_nickname' AS source,
    BTRIM(snc.nickname) AS external_id,
    BTRIM(snc.nickname) AS external_name
FROM ascendany.student_nickname_claims AS snc
WHERE snc.is_active = TRUE
  AND NULLIF(BTRIM(snc.nickname), '') IS NOT NULL
ON CONFLICT (source, external_id)
DO UPDATE SET
    student_id = EXCLUDED.student_id,
    external_name = COALESCE(EXCLUDED.external_name, ascendany.student_identities.external_name);
