CREATE TABLE IF NOT EXISTS ascendany.import_task_events (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id TEXT NOT NULL REFERENCES ascendany.import_tasks(run_id) ON DELETE CASCADE,
    event_type TEXT NOT NULL,
    data JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS import_task_events_run_id_event_id_idx
    ON ascendany.import_task_events (run_id, event_id);
