ALTER TABLE ascendany.user_accounts
    ADD COLUMN IF NOT EXISTS provision_source TEXT NOT NULL DEFAULT 'local',
    ADD COLUMN IF NOT EXISTS local_password_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS local_password_set_at TIMESTAMPTZ NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'user_accounts_provision_source_chk'
          AND conrelid = 'ascendany.user_accounts'::regclass
    ) THEN
        ALTER TABLE ascendany.user_accounts
            ADD CONSTRAINT user_accounts_provision_source_chk
            CHECK (provision_source IN ('local', 'external_sso'));
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS ascendany.external_identity_links (
    link_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider TEXT NOT NULL,
    external_user_id TEXT NOT NULL,
    account_id BIGINT NOT NULL REFERENCES ascendany.user_accounts(account_id) ON DELETE CASCADE,
    external_username TEXT NOT NULL,
    external_display_name TEXT NULL,
    student_id_snapshot TEXT NOT NULL,
    pta_nickname_snapshot TEXT NULL,
    raw_claims JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_login_at TIMESTAMPTZ NULL,
    CONSTRAINT external_identity_links_provider_external_user_id_key
        UNIQUE (provider, external_user_id)
);

CREATE INDEX IF NOT EXISTS external_identity_links_account_id_idx
    ON ascendany.external_identity_links (account_id);

CREATE INDEX IF NOT EXISTS external_identity_links_provider_external_username_idx
    ON ascendany.external_identity_links (provider, external_username);

CREATE TABLE IF NOT EXISTS ascendany.external_sso_jti_consumptions (
    provider TEXT NOT NULL,
    jti TEXT NOT NULL,
    external_user_id TEXT NOT NULL,
    account_id BIGINT NULL REFERENCES ascendany.user_accounts(account_id) ON DELETE SET NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (provider, jti)
);

CREATE INDEX IF NOT EXISTS external_sso_jti_consumptions_expires_at_idx
    ON ascendany.external_sso_jti_consumptions (expires_at);
