CREATE TABLE IF NOT EXISTS ascendany.ai_prompt_templates (
    prompt_key TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    category TEXT NOT NULL DEFAULT 'chat',
    content TEXT NOT NULL,
    default_content TEXT NOT NULL,
    allowed_variables JSONB NOT NULL DEFAULT '[]'::jsonb,
    required_variables JSONB NOT NULL DEFAULT '[]'::jsonb,
    version INTEGER NOT NULL DEFAULT 1 CHECK (version >= 1),
    updated_by TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ascendany.ai_prompt_template_versions (
    version_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prompt_key TEXT NOT NULL REFERENCES ascendany.ai_prompt_templates(prompt_key) ON DELETE CASCADE,
    version INTEGER NOT NULL CHECK (version >= 1),
    content TEXT NOT NULL,
    change_note TEXT,
    updated_by TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (prompt_key, version)
);

CREATE INDEX IF NOT EXISTS ai_prompt_templates_category_idx
    ON ascendany.ai_prompt_templates (category, prompt_key);

CREATE INDEX IF NOT EXISTS ai_prompt_template_versions_prompt_idx
    ON ascendany.ai_prompt_template_versions (prompt_key, version DESC);
