CREATE TABLE IF NOT EXISTS ascendany.recommendation_problem_bank (
    problem_id TEXT PRIMARY KEY,
    title TEXT,
    description TEXT NOT NULL DEFAULT '',
    solution_1 TEXT,
    solution_2 TEXT,
    link TEXT,
    submission_count NUMERIC NOT NULL DEFAULT 0,
    pass_count NUMERIC NOT NULL DEFAULT 0,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    source_hash TEXT NOT NULL,
    meta JSONB NOT NULL DEFAULT '{}'::jsonb,
    imported_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS recommendation_problem_bank_active_idx
    ON ascendany.recommendation_problem_bank (active, problem_id);

CREATE TABLE IF NOT EXISTS ascendany.recommendation_problem_tags (
    problem_id TEXT NOT NULL REFERENCES ascendany.recommendation_problem_bank(problem_id) ON DELETE CASCADE,
    knowledge_point TEXT NOT NULL,
    source TEXT NOT NULL DEFAULT 'legacy_problem_bank',
    confidence NUMERIC NOT NULL DEFAULT 1.0 CHECK (confidence >= 0 AND confidence <= 1),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (problem_id, knowledge_point)
);

CREATE INDEX IF NOT EXISTS recommendation_problem_tags_knowledge_idx
    ON ascendany.recommendation_problem_tags (knowledge_point, problem_id);

CREATE TABLE IF NOT EXISTS ascendany.recommendation_model_runs (
    model_run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status TEXT NOT NULL CHECK (status IN ('queued', 'running', 'success', 'failed', 'cancelled')),
    model_type TEXT NOT NULL DEFAULT 'rgcn',
    config JSONB NOT NULL DEFAULT '{}'::jsonb,
    metrics JSONB NOT NULL DEFAULT '{}'::jsonb,
    artifact_path TEXT,
    error_message TEXT,
    created_by_account_id BIGINT REFERENCES ascendany.user_accounts(account_id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS recommendation_model_runs_status_idx
    ON ascendany.recommendation_model_runs (status, created_at DESC);

CREATE TABLE IF NOT EXISTS ascendany.recommendation_model_events (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_run_id BIGINT NOT NULL REFERENCES ascendany.recommendation_model_runs(model_run_id) ON DELETE CASCADE,
    level TEXT NOT NULL DEFAULT 'info',
    message TEXT NOT NULL,
    data JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS recommendation_model_events_run_idx
    ON ascendany.recommendation_model_events (model_run_id, created_at, event_id);

CREATE TABLE IF NOT EXISTS ascendany.student_recommendation_snapshots (
    student_id BIGINT NOT NULL REFERENCES ascendany.students(student_id) ON DELETE CASCADE,
    model_run_id BIGINT NOT NULL REFERENCES ascendany.recommendation_model_runs(model_run_id) ON DELETE CASCADE,
    items JSONB NOT NULL,
    generated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (student_id, model_run_id)
);

CREATE INDEX IF NOT EXISTS student_recommendation_snapshots_latest_idx
    ON ascendany.student_recommendation_snapshots (student_id, generated_at DESC, model_run_id DESC);

CREATE TABLE IF NOT EXISTS ascendany.student_learning_path_snapshots (
    student_id BIGINT NOT NULL REFERENCES ascendany.students(student_id) ON DELETE CASCADE,
    model_run_id BIGINT NOT NULL REFERENCES ascendany.recommendation_model_runs(model_run_id) ON DELETE CASCADE,
    targets JSONB NOT NULL DEFAULT '[]'::jsonb,
    path JSONB NOT NULL DEFAULT '[]'::jsonb,
    explanations JSONB NOT NULL DEFAULT '{}'::jsonb,
    generated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (student_id, model_run_id)
);

CREATE INDEX IF NOT EXISTS student_learning_path_snapshots_latest_idx
    ON ascendany.student_learning_path_snapshots (student_id, generated_at DESC, model_run_id DESC);
