CREATE TABLE IF NOT EXISTS ascendany.email_verification_codes (
    code_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL,
    email_normalized TEXT GENERATED ALWAYS AS (lower(BTRIM(email))) STORED,
    purpose TEXT NOT NULL CHECK (purpose IN ('registration', 'reset')),
    code TEXT NOT NULL,
    sent_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,
    send_count INTEGER NOT NULL DEFAULT 1 CHECK (send_count >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS email_verification_codes_lookup_idx
    ON ascendany.email_verification_codes (email_normalized, purpose, used_at, expires_at DESC);

CREATE INDEX IF NOT EXISTS email_verification_codes_sent_idx
    ON ascendany.email_verification_codes (email_normalized, purpose, sent_at DESC);

CREATE TABLE IF NOT EXISTS ascendany.oj_problem_testcases (
    testcase_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem_id TEXT NOT NULL REFERENCES ascendany.recommendation_problem_bank(problem_id) ON DELETE CASCADE,
    input_data TEXT NOT NULL DEFAULT '',
    output_data TEXT NOT NULL DEFAULT '',
    is_sample BOOLEAN NOT NULL DEFAULT FALSE,
    weight NUMERIC NOT NULL DEFAULT 1.0,
    time_limit_ms INTEGER NOT NULL DEFAULT 1000,
    memory_limit_kb INTEGER NOT NULL DEFAULT 262144,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    source_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS oj_problem_testcases_problem_hash_uniq
    ON ascendany.oj_problem_testcases (problem_id, source_hash);

CREATE INDEX IF NOT EXISTS oj_problem_testcases_problem_active_idx
    ON ascendany.oj_problem_testcases (problem_id, active, is_sample, testcase_id);

CREATE TABLE IF NOT EXISTS ascendany.oj_submit_records (
    submit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT REFERENCES ascendany.user_accounts(account_id) ON DELETE SET NULL,
    student_entity_id BIGINT REFERENCES ascendany.students(student_id) ON DELETE SET NULL,
    student_id TEXT,
    student_name TEXT,
    problem_id TEXT NOT NULL REFERENCES ascendany.recommendation_problem_bank(problem_id) ON DELETE CASCADE,
    code_content TEXT NOT NULL,
    language TEXT NOT NULL DEFAULT 'C++',
    submit_time TIMESTAMPTZ NOT NULL DEFAULT now(),
    status TEXT NOT NULL DEFAULT 'Pending',
    error_message TEXT,
    score NUMERIC NOT NULL DEFAULT 0,
    score_rate NUMERIC NOT NULL DEFAULT 0,
    memory_kb INTEGER NOT NULL DEFAULT 0,
    runtime_ms INTEGER NOT NULL DEFAULT 0,
    session TEXT NOT NULL DEFAULT '',
    dataset TEXT NOT NULL DEFAULT '',
    global_problem_id TEXT NOT NULL DEFAULT '',
    extra JSONB NOT NULL DEFAULT '{}'::jsonb,
    is_correct BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS oj_submit_records_account_time_idx
    ON ascendany.oj_submit_records (account_id, submit_time DESC);

CREATE INDEX IF NOT EXISTS oj_submit_records_student_time_idx
    ON ascendany.oj_submit_records (student_entity_id, submit_time DESC);

CREATE INDEX IF NOT EXISTS oj_submit_records_problem_time_idx
    ON ascendany.oj_submit_records (problem_id, submit_time DESC);

CREATE INDEX IF NOT EXISTS oj_submit_records_status_idx
    ON ascendany.oj_submit_records (status, submit_time DESC);

CREATE TABLE IF NOT EXISTS ascendany.oj_run_events (
    run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT REFERENCES ascendany.user_accounts(account_id) ON DELETE SET NULL,
    problem_id TEXT REFERENCES ascendany.recommendation_problem_bank(problem_id) ON DELETE SET NULL,
    language TEXT NOT NULL DEFAULT 'C++',
    status TEXT NOT NULL,
    runtime_ms INTEGER NOT NULL DEFAULT 0,
    memory_kb INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS oj_run_events_account_time_idx
    ON ascendany.oj_run_events (account_id, created_at DESC);
