CREATE TABLE IF NOT EXISTS ascendany.external_problems (
    external_problem_pk BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_platform TEXT NOT NULL,
    external_problem_id TEXT NOT NULL,
    title TEXT,
    problem_type TEXT,
    difficulty INTEGER,
    meta JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS external_problems_platform_id_uniq
    ON ascendany.external_problems (source_platform, external_problem_id);

CREATE INDEX IF NOT EXISTS external_problems_platform_title_idx
    ON ascendany.external_problems (source_platform, title);

CREATE TABLE IF NOT EXISTS ascendany.external_problem_versions (
    external_problem_version_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_problem_pk BIGINT NOT NULL REFERENCES ascendany.external_problems(external_problem_pk) ON DELETE CASCADE,
    content_sha256 TEXT NOT NULL,
    title TEXT,
    problem_type TEXT,
    score NUMERIC,
    meta JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS external_problem_versions_problem_hash_uniq
    ON ascendany.external_problem_versions (external_problem_pk, content_sha256);

CREATE INDEX IF NOT EXISTS external_problem_versions_hash_idx
    ON ascendany.external_problem_versions (content_sha256);

CREATE TABLE IF NOT EXISTS ascendany.external_problem_tags (
    external_problem_tag_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_problem_pk BIGINT NOT NULL REFERENCES ascendany.external_problems(external_problem_pk) ON DELETE CASCADE,
    source_platform TEXT NOT NULL,
    external_problem_id TEXT NOT NULL,
    knowledge_point TEXT NOT NULL,
    source TEXT NOT NULL DEFAULT 'pintia_export',
    confidence NUMERIC NOT NULL DEFAULT 1.0 CHECK (confidence >= 0 AND confidence <= 1),
    raw JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS external_problem_tags_platform_problem_tag_uniq
    ON ascendany.external_problem_tags (source_platform, external_problem_id, knowledge_point);

CREATE INDEX IF NOT EXISTS external_problem_tags_knowledge_idx
    ON ascendany.external_problem_tags (knowledge_point, source_platform, external_problem_id);

CREATE TABLE IF NOT EXISTS ascendany.exam_problem_external_links (
    exam_problem_external_link_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exam_id BIGINT NOT NULL REFERENCES ascendany.exams(exam_id) ON DELETE CASCADE,
    exam_problem_id BIGINT NOT NULL REFERENCES ascendany.exam_problems(exam_problem_id) ON DELETE CASCADE,
    external_problem_pk BIGINT NOT NULL REFERENCES ascendany.external_problems(external_problem_pk) ON DELETE RESTRICT,
    external_problem_version_id BIGINT NOT NULL REFERENCES ascendany.external_problem_versions(external_problem_version_id) ON DELETE RESTRICT,
    source_platform TEXT NOT NULL,
    problem_set_id TEXT NOT NULL,
    problem_set_problem_id TEXT NOT NULL,
    external_problem_id TEXT NOT NULL,
    content_sha256 TEXT NOT NULL,
    display_code TEXT,
    raw JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS exam_problem_external_links_exam_problem_uniq
    ON ascendany.exam_problem_external_links (exam_problem_id);

CREATE INDEX IF NOT EXISTS exam_problem_external_links_problem_set_instance_idx
    ON ascendany.exam_problem_external_links (source_platform, problem_set_id, problem_set_problem_id);

CREATE INDEX IF NOT EXISTS exam_problem_external_links_external_problem_idx
    ON ascendany.exam_problem_external_links (external_problem_pk, external_problem_version_id);

CREATE TABLE IF NOT EXISTS ascendany.external_submission_codes (
    external_submission_code_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id BIGINT NOT NULL REFERENCES ascendany.submissions(submission_id) ON DELETE CASCADE,
    source_platform TEXT NOT NULL,
    external_submission_id TEXT NOT NULL,
    language TEXT,
    code_content TEXT NOT NULL,
    code_sha256 TEXT NOT NULL,
    compile_log TEXT,
    case_results JSONB NOT NULL DEFAULT '{}'::jsonb,
    raw JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS external_submission_codes_platform_submission_uniq
    ON ascendany.external_submission_codes (source_platform, external_submission_id);

CREATE INDEX IF NOT EXISTS external_submission_codes_submission_idx
    ON ascendany.external_submission_codes (submission_id);

CREATE INDEX IF NOT EXISTS external_submission_codes_code_sha256_idx
    ON ascendany.external_submission_codes (code_sha256);
