"""DB-backed task manager for long-running import operations.

Task state and event stream are persisted in PostgreSQL so that
multi-worker deployments can read/write the same task data.
"""

from __future__ import annotations

import asyncio
import json
import logging
import threading
import uuid
from dataclasses import dataclass, field
from datetime import UTC, datetime, timedelta
from enum import Enum
from typing import Any, AsyncGenerator

import psycopg
from psycopg.rows import dict_row

from ..core.config import load_settings

logger = logging.getLogger(__name__)


class TaskStatus(str, Enum):
    PENDING = "pending"
    RUNNING = "running"
    DONE = "done"
    FAILED = "failed"


@dataclass
class TaskEvent:
    event_type: str  # "log" | "progress" | "done" | "error" | "heartbeat"
    data: dict[str, Any]
    timestamp: str = field(default_factory=lambda: datetime.now(UTC).isoformat())


@dataclass
class ImportTask:
    run_id: str
    task_type: str  # "import"
    status: TaskStatus = TaskStatus.PENDING
    result: dict[str, Any] | None = None
    created_at: str = field(default_factory=lambda: datetime.now(UTC).isoformat())


class ImportTaskManager:
    """Manages import tasks persisted in PostgreSQL."""

    def __init__(self) -> None:
        settings = load_settings()
        self._dsn = settings.db.build_dsn()
        self._schema_ready = False
        self._schema_lock = threading.Lock()

    def _connect(self) -> psycopg.Connection[Any]:
        return psycopg.connect(self._dsn)

    def _ensure_schema(self) -> None:
        if self._schema_ready:
            return
        with self._schema_lock:
            if self._schema_ready:
                return
            with self._connect() as conn:
                with conn.cursor() as cursor:
                    cursor.execute(
                        """
                        CREATE TABLE IF NOT EXISTS ascendany.import_tasks (
                            run_id TEXT PRIMARY KEY,
                            task_type TEXT NOT NULL,
                            status TEXT NOT NULL,
                            result JSONB NOT NULL DEFAULT '{}'::jsonb,
                            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                            updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
                        )
                        """
                    )
                    cursor.execute(
                        """
                        CREATE INDEX IF NOT EXISTS import_tasks_created_at_idx
                            ON ascendany.import_tasks (created_at DESC)
                        """
                    )
                    cursor.execute(
                        """
                        CREATE TABLE IF NOT EXISTS ascendany.import_task_events (
                            event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            run_id TEXT NOT NULL REFERENCES ascendany.import_tasks(run_id) ON DELETE CASCADE,
                            event_type TEXT NOT NULL,
                            data JSONB NOT NULL DEFAULT '{}'::jsonb,
                            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
                        )
                        """
                    )
                    cursor.execute(
                        """
                        CREATE INDEX IF NOT EXISTS import_task_events_run_id_event_id_idx
                            ON ascendany.import_task_events (run_id, event_id)
                        """
                    )
                conn.commit()
            self._schema_ready = True

    def _coerce_json_object(self, value: Any) -> dict[str, Any]:
        if isinstance(value, dict):
            return value
        if isinstance(value, str):
            try:
                parsed = json.loads(value)
            except json.JSONDecodeError:
                return {}
            return parsed if isinstance(parsed, dict) else {}
        return {}

    def create_task(self, task_type: str) -> str:
        self._ensure_schema()
        run_id = uuid.uuid4().hex[:12]
        with self._connect() as conn:
            with conn.cursor() as cursor:
                cursor.execute(
                    """
                    INSERT INTO ascendany.import_tasks (run_id, task_type, status)
                    VALUES (%s, %s, %s)
                    """,
                    (run_id, task_type, TaskStatus.PENDING.value),
                )
            conn.commit()
        return run_id

    def get_task(self, run_id: str) -> ImportTask | None:
        self._ensure_schema()
        with self._connect() as conn:
            with conn.cursor(row_factory=dict_row) as cursor:
                cursor.execute(
                    """
                    SELECT run_id, task_type, status, result, created_at
                    FROM ascendany.import_tasks
                    WHERE run_id = %s
                    LIMIT 1
                    """,
                    (run_id,),
                )
                row = cursor.fetchone()
        if not row:
            return None
        status_raw = str(row.get("status", TaskStatus.PENDING.value))
        try:
            status = TaskStatus(status_raw)
        except ValueError:
            status = TaskStatus.PENDING
        result = self._coerce_json_object(row.get("result"))
        created_at = row.get("created_at")
        created_iso = (
            created_at.isoformat()
            if isinstance(created_at, datetime)
            else datetime.now(UTC).isoformat()
        )
        return ImportTask(
            run_id=str(row["run_id"]),
            task_type=str(row["task_type"]),
            status=status,
            result=result,
            created_at=created_iso,
        )

    def emit(self, run_id: str, event: TaskEvent) -> None:
        self._ensure_schema()
        with self._connect() as conn:
            with conn.cursor() as cursor:
                cursor.execute(
                    """
                    INSERT INTO ascendany.import_task_events (run_id, event_type, data)
                    VALUES (%s, %s, %s::jsonb)
                    """,
                    (
                        run_id,
                        event.event_type,
                        json.dumps(event.data, ensure_ascii=False),
                    ),
                )
                cursor.execute(
                    """
                    UPDATE ascendany.import_tasks
                    SET updated_at = now()
                    WHERE run_id = %s
                    """,
                    (run_id,),
                )
            conn.commit()

    def emit_log(
        self,
        run_id: str,
        level: str,
        message: str,
    ) -> None:
        self.emit(
            run_id,
            TaskEvent(
                event_type="log",
                data={
                    "level": level,
                    "message": message,
                },
            ),
        )

    def emit_progress(
        self,
        run_id: str,
        current: int,
        total: int,
        exam_type: str | None = None,
        source_path: str | None = None,
        phase: str | None = None,
    ) -> None:
        self.emit(
            run_id,
            TaskEvent(
                event_type="progress",
                data={
                    "current": current,
                    "total": total,
                    "examType": exam_type,
                    "sourcePath": source_path,
                    "phase": phase,
                },
            ),
        )

    def emit_done(self, run_id: str, data: dict[str, Any]) -> None:
        self._ensure_schema()
        with self._connect() as conn:
            with conn.cursor() as cursor:
                cursor.execute(
                    """
                    UPDATE ascendany.import_tasks
                    SET status = %s,
                        result = %s::jsonb,
                        updated_at = now()
                    WHERE run_id = %s
                    """,
                    (TaskStatus.DONE.value, json.dumps(data, ensure_ascii=False), run_id),
                )
                cursor.execute(
                    """
                    INSERT INTO ascendany.import_task_events (run_id, event_type, data)
                    VALUES (%s, 'done', %s::jsonb)
                    """,
                    (run_id, json.dumps(data, ensure_ascii=False)),
                )
            conn.commit()

    def emit_error(self, run_id: str, message: str) -> None:
        self._ensure_schema()
        payload = {"message": message}
        with self._connect() as conn:
            with conn.cursor() as cursor:
                cursor.execute(
                    """
                    UPDATE ascendany.import_tasks
                    SET status = %s,
                        result = %s::jsonb,
                        updated_at = now()
                    WHERE run_id = %s
                    """,
                    (
                        TaskStatus.FAILED.value,
                        json.dumps({"error": message}, ensure_ascii=False),
                        run_id,
                    ),
                )
                cursor.execute(
                    """
                    INSERT INTO ascendany.import_task_events (run_id, event_type, data)
                    VALUES (%s, 'error', %s::jsonb)
                    """,
                    (run_id, json.dumps(payload, ensure_ascii=False)),
                )
            conn.commit()

    def mark_running(self, run_id: str) -> None:
        self._ensure_schema()
        with self._connect() as conn:
            with conn.cursor() as cursor:
                cursor.execute(
                    """
                    UPDATE ascendany.import_tasks
                    SET status = %s,
                        updated_at = now()
                    WHERE run_id = %s
                    """,
                    (TaskStatus.RUNNING.value, run_id),
                )
            conn.commit()

    def _fetch_events_and_status(
        self,
        run_id: str,
        after_event_id: int,
        limit: int = 100,
    ) -> tuple[list[dict[str, Any]], str | None]:
        self._ensure_schema()
        with self._connect() as conn:
            with conn.cursor(row_factory=dict_row) as cursor:
                cursor.execute(
                    """
                    SELECT status
                    FROM ascendany.import_tasks
                    WHERE run_id = %s
                    LIMIT 1
                    """,
                    (run_id,),
                )
                task_row = cursor.fetchone()
                if not task_row:
                    return [], None

                cursor.execute(
                    """
                    SELECT event_id, event_type, data, created_at
                    FROM ascendany.import_task_events
                    WHERE run_id = %s
                      AND event_id > %s
                    ORDER BY event_id ASC
                    LIMIT %s
                    """,
                    (run_id, after_event_id, limit),
                )
                rows = cursor.fetchall()
        events: list[dict[str, Any]] = []
        for row in rows:
            created_at = row.get("created_at")
            created_iso = (
                created_at.isoformat()
                if isinstance(created_at, datetime)
                else datetime.now(UTC).isoformat()
            )
            events.append(
                {
                    "event_id": int(row["event_id"]),
                    "event_type": str(row["event_type"]),
                    "data": self._coerce_json_object(row.get("data")),
                    "timestamp": created_iso,
                }
            )
        return events, str(task_row["status"])

    async def event_stream(
        self, run_id: str, heartbeat_seconds: float = 15.0
    ) -> AsyncGenerator[str, None]:
        """Yields SSE-formatted strings from DB-backed task events."""
        task = await asyncio.to_thread(self.get_task, run_id)
        if task is None:
            yield _sse_format("error", {"message": f"Task {run_id} not found"})
            return

        last_event_id = 0
        last_heartbeat_at = datetime.now(UTC)
        while True:
            events, status = await asyncio.to_thread(
                self._fetch_events_and_status,
                run_id,
                last_event_id,
            )

            if status is None:
                yield _sse_format("error", {"message": f"Task {run_id} not found"})
                return

            if events:
                for event in events:
                    last_event_id = max(last_event_id, int(event["event_id"]))
                    payload = dict(event["data"])
                    payload["timestamp"] = event["timestamp"]
                    yield _sse_format(str(event["event_type"]), payload)
                continue

            now = datetime.now(UTC)
            if (now - last_heartbeat_at).total_seconds() >= heartbeat_seconds:
                yield _sse_format("heartbeat", {"ts": datetime.now(UTC).isoformat()})
                last_heartbeat_at = now

            if status in {TaskStatus.DONE.value, TaskStatus.FAILED.value}:
                return

            await asyncio.sleep(0.8)

    def cleanup_old_tasks(self, max_age_seconds: int = 3600) -> int:
        """Remove finished tasks older than max_age_seconds."""
        self._ensure_schema()
        threshold = datetime.now(UTC) - timedelta(seconds=max_age_seconds)
        with self._connect() as conn:
            with conn.cursor() as cursor:
                cursor.execute(
                    """
                    DELETE FROM ascendany.import_tasks
                    WHERE status IN (%s, %s)
                      AND created_at < %s
                    """,
                    (TaskStatus.DONE.value, TaskStatus.FAILED.value, threshold),
                )
                removed = cursor.rowcount or 0
            conn.commit()
        return int(removed)

    def list_tasks(self, limit: int = 20) -> list[dict[str, Any]]:
        self._ensure_schema()
        with self._connect() as conn:
            with conn.cursor(row_factory=dict_row) as cursor:
                cursor.execute(
                    """
                    SELECT run_id, task_type, status, created_at, result
                    FROM ascendany.import_tasks
                    ORDER BY created_at DESC
                    LIMIT %s
                    """,
                    (limit,),
                )
                rows = cursor.fetchall()

        items: list[dict[str, Any]] = []
        for row in rows:
            created_at = row.get("created_at")
            created_iso = (
                created_at.isoformat()
                if isinstance(created_at, datetime)
                else datetime.now(UTC).isoformat()
            )
            items.append(
                {
                    "runId": str(row["run_id"]),
                    "taskType": str(row["task_type"]),
                    "status": str(row["status"]),
                    "createdAt": created_iso,
                    "result": self._coerce_json_object(row.get("result")),
                }
            )
        return items


# ── Global singleton ─────────────────────────────────────

_task_manager: ImportTaskManager | None = None
_manager_lock = threading.Lock()


def get_task_manager() -> ImportTaskManager:
    global _task_manager
    if _task_manager is None:
        with _manager_lock:
            if _task_manager is None:
                _task_manager = ImportTaskManager()
    return _task_manager


# ── SSE formatting ────────────────────────────────────────

def _sse_format(event_type: str, data: dict[str, Any]) -> str:
    payload = json.dumps(data, ensure_ascii=False, default=str)
    return f"event: {event_type}\ndata: {payload}\n\n"
