package main

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

const marker = "-- ascendany-go-verifier-begin\n"

func main() {
	sourcePath := filepath.Join("..", "..", "..", "db", "roles", "verify_v2_roles.sql")
	contents, err := os.ReadFile(sourcePath)
	if err != nil {
		panic(fmt.Errorf("read %s: %w", sourcePath, err))
	}
	_, body, found := strings.Cut(string(contents), marker)
	if !found || strings.Contains(body, "\\set") || strings.Contains(body, "\\if") {
		panic("canonical verifier marker is missing or leaves psql commands in the Go body")
	}
	generated := "// Code generated by go generate; DO NOT EDIT.\n\n" +
		"package databasecontract\n\n" +
		"const verifierSQL = " + strconv.Quote(body) + "\n"
	formatted, err := format.Source([]byte(generated))
	if err != nil {
		panic(fmt.Errorf("format generated verifier: %w", err))
	}
	if err := os.WriteFile("contract_generated.go", formatted, 0o644); err != nil {
		panic(fmt.Errorf("write generated verifier: %w", err))
	}
}
